package com.example.fitnessworkouttracker.exercise;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "exercises")
public class Exercise {
    // I'm mapping this class to my "exercises" table with JPA
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // I learned my id is auto-generated by the database

    @Column(nullable = false, unique = true, length = 100)
    private String name; // I keep my exercise name unique and required

    @Column(nullable = false, length = 50)
    private String category; // I'm grouping by category like Chest, Legs, Back

    @Column(length = 500)
    private String description; // my optional longer description

    protected Exercise() { // I need this empty constructor so JPA can create me
    }

    public Exercise(String name, String category, String description) {
        this.name = name;
        this.category = category;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
